force-app/main/default/objects/Sensor__c/Sensor__c.object-meta.xml
<CustomObject>
    <label>Sensor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor_Event__c/Sensor_Event__c.object-meta.xml
<CustomObject>
    <label>Sensor Event</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensor Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor_Event__c/fields/Modulus_Difference_Vectors__c.field-meta.xml
<CustomField>
    <fullName>Modulus_Difference_Vectors__c</fullName>
    <formula>SQRT(x__c * x__c + y__c * y__c + z__c * z__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Modulus_Difference_Vectors</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SensorPickListController.cls
public with sharing class SensorPickListController {

    @AuraEnabled(cacheable = true)
    public static List<Sensor__c> getAllSensors() {

        if(!Schema.sObjectType.Sensor__c.isAccessible()) {
            throw new System.NoAccessException();
        }

        String [] expenseAccessFields = new String [] {'Id','Name'};

        Map<String,Schema.SObjectField> m = Schema.SObjectType.Sensor__c.fields.getMap();
 
        for (String fieldToCheck : expenseAccessFields) {
            if (!m.get(fieldToCheck).getDescribe().isAccessible()) {
                throw new System.NoAccessException();
            }
        }

        List<Sensor__c> sensors = [SELECT Name FROM Sensor__c];
        return sensors;
    }

    @AuraEnabled(cacheable = true)
    public static List<Sensor_Event__c> getSensorEvents(String sensorId) {

        if(!Schema.SObjectType.Sensor_Event__c.isAccessible()) {
            throw new System.NoAccessException();
        }

        String [] expenseAccessFields = new String [] {'Id','Name', 'X__c', 'Y__c', 'Z__c', 'Modulus_Difference_Vectors__c'};

        Map<String,Schema.SObjectField> m = Schema.SObjectType.Sensor_Event__c.fields.getMap();
 
        for (String fieldToCheck : expenseAccessFields) {
            if (!m.get(fieldToCheck).getDescribe().isAccessible()) {
                throw new System.NoAccessException();
            }
        }

        List<Sensor_Event__c> events = [SELECT Name, X__c, Y__c, Z__c,	Modulus_Difference_Vectors__c 
                                        FROM Sensor_Event__c WHERE Sensor__c =: sensorId];
        return events;
    }

}